<?php
/** NCK WEALTH — YouTube latest long-form feed (API-free). */
define('NCK_APP', true);
error_reporting(E_ALL); ini_set('display_errors','0');
header('Content-Type: application/json; charset=UTF-8');
header('X-Content-Type-Options: nosniff');
function respond(int $status, array $payload): void { http_response_code($status); echo json_encode($payload, JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE); exit; }
$config = require __DIR__.'/youtube-config.php';
$handle = ltrim(trim((string)($config['channel_handle'] ?? 'NCKWEALTH')), '@');
$maxResults=max(1,min(12,(int)($config['long_results']??4))); $cacheTtl=max(60,(int)($config['cache_ttl_seconds']??300));
$cacheDir=__DIR__.'/cache'; if(!is_dir($cacheDir)) @mkdir($cacheDir,0755,true); $cacheFile=$cacheDir.'/youtube-long-cache.json'; $lockFile=$cacheDir.'/youtube-long.lock';
function cache_read(string $f):?array { if(!is_file($f))return null; $d=json_decode((string)@file_get_contents($f),true); return is_array($d)&&isset($d['videos'])&&is_array($d['videos'])?$d:null; }
function http_get(string $url):array { $headers=['Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8','Accept-Language: en-US,en;q=0.9']; if(function_exists('curl_init')){ $ch=curl_init($url); curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>3,CURLOPT_TIMEOUT=>12,CURLOPT_CONNECTTIMEOUT=>6,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_HTTPHEADER=>$headers,CURLOPT_USERAGENT=>'Mozilla/5.0 (compatible; NCKWEALTH/1.0; +https://nckwealth.com)']); $body=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$err=curl_error($ch);curl_close($ch);return[$status,(string)$body,$err]; } $ctx=stream_context_create(['http'=>['method'=>'GET','timeout'=>12,'header'=>implode("\r\n",$headers),'user_agent'=>'Mozilla/5.0 (compatible; NCKWEALTH/1.0)']]);$body=@file_get_contents($url,false,$ctx);return[$body===false?0:200,$body===false?'':$body,$body===false?'http_request_failed':'']; }
function txt($v):string { if(!is_array($v))return ''; if(isset($v['simpleText'])&&is_string($v['simpleText']))return$v['simpleText']; if(isset($v['content'])&&is_string($v['content']))return$v['content']; if(isset($v['runs'])&&is_array($v['runs'])){ $s='';foreach($v['runs'] as $r)if(is_array($r)&&isset($r['text']))$s.=(string)$r['text'];return$s;} return ''; }
function vid(string $id):string{return preg_match('/^[A-Za-z0-9_-]{11}$/',$id)?$id:'';}
function collect($node,array &$videos,array &$seen):void { if(!is_array($node))return; $id='';$url=''; if(isset($node['videoId']))$id=vid((string)$node['videoId']); if(isset($node['navigationEndpoint']['commandMetadata']['webCommandMetadata']['url'])){$url=(string)$node['navigationEndpoint']['commandMetadata']['webCommandMetadata']['url'];if(preg_match('~/watch\?v=([A-Za-z0-9_-]{11})~',$url,$m))$id=$m[1];} if($id && strpos($url,'/shorts/')===false && !isset($node['reelWatchEndpoint']) && !isset($node['shortsLockupViewModel']) && !isset($node['navigationEndpoint']['reelWatchEndpoint']) && !isset($seen[$id])){ $title=txt($node['title']??null); if($title==='')$title=txt($node['headline']??null); if($title==='')$title=txt($node['overlayMetadata']['primaryText']??null); $thumb='';$ths=$node['thumbnail']['thumbnails']??[];if(is_array($ths)&&$ths){$last=end($ths);if(is_array($last)&&isset($last['url']))$thumb=(string)$last['url'];} if($thumb==='')$thumb='https://i.ytimg.com/vi/'.$id.'/hqdefault.jpg'; $videos[]=['id'=>$id,'title'=>$title!==''?$title:'NCK WEALTH Video','publishedAt'=>txt($node['publishedTimeText']??null),'thumbnail'=>$thumb,'watchUrl'=>'https://www.youtube.com/watch?v='.$id,'embedUrl'=>'https://www.youtube.com/embed/'.$id];$seen[$id]=true;} foreach($node as $v)if(is_array($v))collect($v,$videos,$seen); }
function initial(string $html):?array { $p=strpos($html,'var ytInitialData = '); if($p===false)$p=strpos($html,'ytInitialData = '); if($p===false)return null; $p=strpos($html,'{',$p);$e=strpos($html,'</script>',$p);if($p===false||$e===false)return null;$j=trim(substr($html,$p,$e-$p));$j=preg_replace('/;\s*$/','',$j);$d=json_decode($j,true);return is_array($d)?$d:null; }
$cached=cache_read($cacheFile); if($cached&&isset($cached['generated_at'])&&(time()-(int)$cached['generated_at'])<$cacheTtl)respond(200,['success'=>true,'videos'=>array_slice($cached['videos'],0,$maxResults),'cached'=>true,'generated_at'=>$cached['generated_at'],'source'=>'youtube-videos-page']);
$fh=@fopen($lockFile,'c');$got=$fh&&flock($fh,LOCK_EX|LOCK_NB);if(!$got){if($fh)fclose($fh);if($cached)respond(200,['success'=>true,'videos'=>array_slice($cached['videos'],0,$maxResults),'cached'=>true,'stale'=>true]);respond(200,['success'=>true,'videos'=>[],'refreshing'=>true]);}
try{$url='https://www.youtube.com/@'.rawurlencode($handle).'/videos?hl=en';[$status,$html,$err]=http_get($url);if($status<200||$status>=300||$html==='')throw new RuntimeException('youtube_videos_page_failed');$data=initial($html);$videos=[];$seen=[];if($data)collect($data,$videos,$seen);if(!$videos&&preg_match_all('~(?:/watch\?v=)([A-Za-z0-9_-]{11})~',$html,$m)){foreach(array_values(array_unique($m[1])) as $id){if(isset($seen[$id]))continue;$videos[]=['id'=>$id,'title'=>'NCK WEALTH Video','publishedAt'=>'','thumbnail'=>'https://i.ytimg.com/vi/'.$id.'/hqdefault.jpg','watchUrl'=>'https://www.youtube.com/watch?v='.$id,'embedUrl'=>'https://www.youtube.com/embed/'.$id];$seen[$id]=true;}}if(!$videos)throw new RuntimeException('no_videos_found');$videos=array_slice($videos,0,$maxResults);$result=['generated_at'=>time(),'videos'=>$videos];@file_put_contents($cacheFile,json_encode($result,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),LOCK_EX);flock($fh,LOCK_UN);fclose($fh);respond(200,['success'=>true,'videos'=>$videos,'cached'=>false,'generated_at'=>$result['generated_at'],'source'=>'youtube-videos-page']);}catch(Throwable $e){if($got&&$fh){flock($fh,LOCK_UN);fclose($fh);}if($cached)respond(200,['success'=>true,'videos'=>array_slice($cached['videos'],0,$maxResults),'cached'=>true,'stale'=>true]);respond(502,['success'=>false,'error'=>'fetch_failed']);}
